baseurl = "https://cosx.org/"
languageCode = "zh-CN"
title = "统计之都"
theme = "hugo-xmag"
disqusShortname = ""
googleAnalytics = "UA-1988641-11"
paginate = 12
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage = true
enableEmoji = true
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[blackfriday]
  extensionsmask = ["noIntraEmphasis"]

[permalinks]
  post = "/:year/:month/:slug/"

[[menu.main]]
  name = "首页"
  url = "/"
  weight = 1

[[menu.main]]
  name = "论坛"
  url = "https://d.cosx.org"
  weight = 3

[params.banner]
  src = "/img/logo-full.png"
  alt = "统计之都 标志"

[params.text]
  back = "&larr; 返回首页"
  edit = "编辑本页 &rarr;"
  tags = "关键词："
  comment = "发表/查看评论"
  truncated = "&hellip;&hellip;"

[params]
	copyright = "统计之都 版权所有 2006 - 2017"
	description = "中国统计学门户网站，免费统计学服务平台"

  summary_length = 200
  github_edit = "https://github.com/cosname/cosx.org/edit/master/content/"
  comment_url = "https://d.cosx.org/d/"
  footer = "&copy; [统计之都](https://cosx.org) 2006 - 2017 | [新浪微博](http://weibo.com/cosname) | [Github](https://github.com/cosname) | [Twitter](https://twitter.com/cos_name) | [Google+](https://plus.google.com/110727350576315935180) | [LinkedIn](https://www.linkedin.com/groups/4564122)"
